data :
  name : "blob"
  path : "data/datasets/blob_dataset.pth"
  num_classes : 3
  num_samples : 1000

input_ball:
  norm : "Linf"
  epsilon : 1

network :
  name : "blob_nn"
  path : "data/models/blob_adv_blob_nn.pt"
  K : 3
  n :
  - 2
  - 10
  - 10
  - 3

models :
  # - certification_model_name : "MdSDP"
  #   cuts : 
  #   - "RLT"
  #   - "triangularization"
  #   RLT_prop : 1
  #   all_combinations_cuts : false
  #   MATRIX_BY_LAYERS: true
  #   LAST_LAYER: false
  #   use_fusion: true  # Whether to use the fusion API for MOSEK
  #   use_callback : false # Whether to use the callback for MOSEK
  #   use_active_neurons: false # Whether to use active neurons in the certification problem as variables
  #   use_inactive_neurons : false # Whether to use inactive neurons in the certification problem as variables
  #   keep_penultimate_actives : false
  #   write_model : true


  - certification_model_name : "MdQuad"
    LAST_LAYER: false
    use_active_neurons: true # Whether to use active neurons in the certification problem as variables
    use_inactive_neurons : true # Whether to use inactive neurons in the certification problem as variables
    bounds_method: "alpha-CROWN"  # Method to compute bounds, options: "IBP", "GREAT_BOUNDS", "GREAT_BOUNDS_LIN"


  # - certification_model_name : "LanQuad"
  #   LAST_LAYER: false
  #   use_active_neurons: true # Whether to use active neurons in the certification problem as variables
  #   use_inactive_neurons : true # Whether to use inactive neurons in the certification problem as variables
  #   bounds_method: "alpha-CROWN"  # Method to compute bounds, options: "IBP", "GREAT_BOUNDS", "GREAT_BOUNDS_LIN"
