data :
  name : "blob"
  path : "data/datasets/blob_dataset.pth"
  num_classes : 3
  num_samples : 1000

input_ball:
  norm : "Linf"
  epsilon : 0.5

divide_run : 1

network :
  name : "blob_nn_4x10"
  path : "data/models/blob_adv_blob_nn_4x10.pt"
  K : 5
  n :
  - 2
  - 10
  - 10
  - 10
  - 10
  - 3

models :
  - certification_model_name : "MdSDP"
    write_model: true
    cuts :
    - "RLT"
    - "triangularization"
    - "McCormick_beta_z"
    - "beta_logits_comparaison"
    RLT_props :
    - 1.
    all_combinations_cuts : false
    MATRIX_BY_LAYERS: true
    LAST_LAYER: false
    use_fusion: true  # Whether to use the fusion API for MOSEK
    use_callback : false # Whether to use the callback for MOSEK
    use_active_neurons: false # Whether to use active neurons in the certification problem as variables
    #ultimate_layer_use_active_neurons: 5 # Whether to use active neurons in the ultimate layer in the certification problem as variables
    use_inactive_neurons : false # Whether to use inactive neurons in the certification problem as variables
    keep_penultimate_actives : true # Whether to keep the penultimate layer active neurons in the certification problem
    # bounds_file: "alpha-CROWN"  # Folder where precomputed bounds are stored
    bounds_method: "alpha-CROWN"   #"alpha-CROWN"  # Method to compute bounds, options: "IBP", "GREAT_BOUNDS", "GREAT_BOUNDS_LIN"
    bounds_n_runs : 10 # Number of runs to compute bounds, useful when the method is non-deterministic (e.g., alpha-CROWN with random alpha initialization)
   # solver_time_limit : 10 # Time limit for MOSEK in seconds, set to None for no limit
  
  # # SDPt
  # - certification_model_name : "LanSDP"
  #   solver: "mosek_fusion"
  #   cuts :
  #   - "RLT"
  #   - "triangularization"
  #   RLT_props : 
  #   - 0.1
  #   all_combinations_cuts : false
  #   MATRIX_BY_LAYERS: true
  #   LAST_LAYER: false
  #   use_fusion: false  # Whether to use the fusion API for MOSEK
  #   use_callback : false # Whether to use the callback for MOSEK
  #   use_active_neurons: true # Whether to use active neurons in the certification problem as variables
  #   use_inactive_neurons : false # Whether to use inactive neurons in the certification problem as variables
  #   keep_penultimate_actives : true
  #   bounds_method: "alpha-CROWN"  # Method to compute bounds, options: "IBP", "GREAT_BOUNDS", "GREAT_BOUNDS_LIN"



  # - certification_model_name : "MdQuad"
  #   LAST_LAYER: false
  #   use_active_neurons: true # Whether to use active neurons in the certification problem as variables
  #   use_inactive_neurons : false # Whether to use inactive neurons in the certification problem as variables
  #   bounds_method: "alpha-CROWN"  # Method to compute bounds, options: "IBP", "GREAT_BOUNDS", "GREAT_BOUNDS_LIN"
