data :
  name : "mnist"
  path :  "data/datasets/MNIST/ConcatMNIST/50_classes/concatmnist_subset_1_per_class.pth"
  num_classes : 50
  num_samples : 50

divide_run : 2

input_ball : 
  epsilon : 0.01
  norm : "Linf"

network :
  name : "concatmnist-6x100-50-classes"
  path : "data/models/concatmnist_adv_concatmnist-6x100-50-classes.pt"
  K : 7
  n : 
    - 784
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 50



models :
  # # SDP-IP
  # - certification_model_name : "LanSDP"
  #   # cuts : 
  #   # - "RLT"
  #   # - "triangularization"
  #   # RLT_props : 
  #   # - 0.1
  #   # - 0.2
  #   all_combinations_cuts : false
  #   MATRIX_BY_LAYERS: false
  #   LAST_LAYER: false
  #   use_fusion: false  # Whether to use the fusion API for MOSEK
  #   use_callback : false # Whether to use the callback for MOSEK
  #   use_active_neurons: true # Whether to use active neurons in the certification problem as variables
  #   use_inactive_neurons : true # Whether to use inactive neurons in the certification problem as variables
  #   bounds_method: "alpha-CROWN"  # Method to compute bounds, options: "IBP", "GREAT_BOUNDS", "GREAT_BOUNDS_LIN"

  # # SDP-Layer
  # - certification_model_name : "LanSDP"
  #   cuts : 
  #   - "triangularization"
  #   # RLT_props : 
  #   # - 0.
  #   all_combinations_cuts : false
  #   MATRIX_BY_LAYERS: true
  #   LAST_LAYER: false
  #   use_fusion: false  # Whether to use the fusion API for MOSEK
  #   use_callback : false # Whether to use the callback for MOSEK
  #   use_active_neurons: true # Whether to use active neurons in the certification problem as variables
  #   use_inactive_neurons : false # Whether to use inactive neurons in the certification problem as variables
  #   bounds_method: "alpha-CROWN"  # Method to compute bounds, options: "IBP", "GREAT_BOUNDS", "GREAT_BOUNDS_LIN"

  # # SDPt
  # - certification_model_name : "LanSDP"
  #   cuts : 
  #   - "RLT"
  #   - "triangularization"
  #   RLT_props : 
  #   - 0.1
  #   # - 0.2
  #   # - 0.3
  #   # - 0.5
  #   all_combinations_cuts : false
  #   MATRIX_BY_LAYERS: true
  #   LAST_LAYER: false
  #   use_fusion: false  # Whether to use the fusion API for MOSEK
  #   use_callback : false # Whether to use the callback for MOSEK
  #   use_active_neurons: true # Whether to use active neurons in the certification problem as variables
  #   use_inactive_neurons : false # Whether to use inactive neurons in the certification problem as variables
  #   keep_penultimate_actives : true
  #   bounds_method: "alpha-CROWN"  # Method to compute bounds, options: "IBP", "GREAT_BOUNDS", "GREAT_BOUNDS_LIN"




  - certification_model_name : "MdSDP"
    write_model: true
    cuts : 
    - "RLT"
    - "triangularization"
    - "McCormick_beta_z"
    - "beta_logits_comparaison"
    RLT_props :
    - 1.
    all_combinations_cuts : false
    MATRIX_BY_LAYERS: true
    LAST_LAYER: false
    use_fusion: false  # Whether to use the fusion API for MOSEK
    use_callback : false # Whether to use the callback for MOSEK
    use_active_neurons: true # Whether to use active neurons in the certification problem as variables
    #ultimate_layer_use_active_neurons: 5 # Whether to use active neurons in the ultimate layer in the certification problem as variables
    use_inactive_neurons : false # Whether to use inactive neurons in the certification problem as variables
    keep_penultimate_actives : true # Whether to keep the penultimate layer active neurons in the certification problem
    # bounds_file: "data/bounds/blob_4x10-0.5_linf.csv"  # Folder where precomputed bounds are stored
    bounds_method: "alpha-CROWN"   #"alpha-CROWN"  # Method to compute bounds, options: "IBP", "GREAT_BOUNDS", "GREAT_BOUNDS_LIN"
   # solver_time_limit : 10 # Time limit for MOSEK in seconds, set to None for no limit
