data :
  name : "cifar100"
  path : "data/datasets/cifar100_subset_10_per_class.pth"
  num_classes : 100
  num_samples : 1000

input_ball:
  # epsilon : 0.03137 # 8/255
  epsilon : 0.015686 # 4/255
  # epsilon : 0.007843 # 2/255
  # epsilon : 0.003922 # 1/255
  norm : "Linf"

divide_run : 1


network :
  name : "fcna-cifar100"
  path : "data/models/cifar100_adv_fcna-cifar100.pt"
  K : 3
  n :
    - 3072
    - 20
    - 20
    - 100



models :
  # # SDP-IP
  # - certification_model_type : "TargetedSDP"
  #   # cuts : 
  #   # - "RLT"
  #   # - "triangularization"
  #   # RLT_props : 
  #   # - 0.1
  #   # - 0.2
  #   all_combinations_cuts : false
  #   MATRIX_BY_LAYERS: false
  #   LAST_LAYER: false
  #   use_fusion: false  # Whether to use the fusion API for MOSEK
  #   use_callback : false # Whether to use the callback for MOSEK
  #   use_active_neurons: true # Whether to use active neurons in the certification problem as variables
  #   use_inactive_neurons : true # Whether to use inactive neurons in the certification problem as variables
  #   bounds_method: "alpha-CROWN"  # Method to compute bounds, options: "IBP", "GREAT_BOUNDS", "GREAT_BOUNDS_LIN"

  # # SDP-Layer
  # - certification_model_type : "TargetedSDP"
  #   cuts : 
  #   - "triangularization"                                                                                                                                       
  #   # RLT_props : 
  #   # - 0.
  #   all_combinations_cuts : false
  #   MATRIX_BY_LAYERS: true
  #   LAST_LAYER: false
  #   use_fusion: false  # Whether to use the fusion API for MOSEK
  #   use_callback : false # Whether to use the callback for MOSEK
  #   use_active_neurons: true # Whether to use active neurons in the certification problem as variables
  #   use_inactive_neurons : false # Whether to use inactive neurons in the certification problem as variables
  #   bounds_method: "alpha-CROWN"  # Method to compute bounds, options: "IBP", "GREAT_BOUNDS", "GREAT_BOUNDS_LIN"

  # # SDPt
  # - certification_model_type : "TargetedSDP"
  #   cuts : 
  #   - "RLT"
  #   - "triangularization"
  #   RLT_props : 
  #   - 0.1
  #   all_combinations_cuts : false
  #   MATRIX_BY_LAYERS: true
  #   LAST_LAYER: false
  #   use_fusion: false  # Whether to use the fusion API for MOSEK
  #   use_callback : false # Whether to use the callback for MOSEK
  #   use_active_neurons: true # Whether to use active neurons in the certification problem as variables
  #   use_inactive_neurons : false # Whether to use inactive neurons in the certification problem as variables
  #   keep_penultimate_actives : true
  #   bounds_method: "alpha-CROWN"  # Method to compute bounds, options: "IBP", "GREAT_BOUNDS", "GREAT_BOUNDS_LIN"


  - certification_model_type : "UntargetedSDP"
    write_model: true
    cuts : 
    - "RLT"
    - "triangularization"
    - "McCormick_beta_z"
    - "beta_logits_comparaison"
    RLT_props :
    - 1.
    all_combinations_cuts : false
    MATRIX_BY_LAYERS: true
    LAST_LAYER: false
    use_fusion: false  # Whether to use the fusion API for MOSEK
    use_callback : false # Whether to use the callback for MOSEK
    use_active_neurons: false # Whether to use active neurons in the certification problem as variables
    #ultimate_layer_use_active_neurons: 5 # Whether to use active neurons in the ultimate layer in the certification problem as variables
    use_inactive_neurons : false # Whether to use inactive neurons in the certification problem as variables
    keep_penultimate_actives : true # Whether to keep the penultimate layer active neurons in the certification problem
    # bounds_file: "data/bounds/blob_4x10-0.5_linf.csv"  # Folder where precomputed bounds are stored
    bounds_method: "alpha-CROWN"   #"alpha-CROWN"  # Method to compute bounds, options: "IBP", "GREAT_BOUNDS", "GREAT_BOUNDS_LIN"
   # solver_time_limit : 10 # Time limit for MOSEK in seconds, set to None for no limit




  # - certification_model_type : "ClassicLP"
  #   LAST_LAYER: false
  #   use_active_neurons: true # Whether to use active neurons in the certification problem as variables
  #   use_inactive_neurons : false # Whether to use inactive neurons in the certification problem as variables
  #   bounds_method: "alpha-CROWN"  # Method to compute bounds, options: "IBP", "GREAT_BOUNDS", "GREAT_BOUNDS_LIN"

