data : "moon"
train_path  : "data/datasets/moon_dataset.pth"
test_path   : "data/datasets/moon_dataset.pth"
evaluate_robustness_path : "data/datasets/moon_dataset.pth"
num_classes : 2
# Projected Gradient Descent (PGD)
adversarial_attack : "PGD"
epsilon : 0.05
epsilon_test : 0.05
alpha : 0.005
steps : 40
random_start : true
num_epochs : 200
lr : 0.001
batch_size : 128
K : 5
n : 
  - 2
  - 20
  - 20
  - 20
  - 20
  - 2
name_network :  "moon_4x20"


  